sonar.projectKey=jerem-gt_cash-ctrl
sonar.organization=jerem-gt

sonar.sources=server/src,client/src
sonar.tests=server/src
sonar.test.inclusions=**/*.test.ts

sonar.javascript.lcov.reportPaths=server/coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
